ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'TRON';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'TRON_NILE';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'TRON_SHASTA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'ZKSYNC';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'ZKSYNC_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'LINEA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'LINEA_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'SCROLL';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'SCROLL_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'MANTLE';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'MANTLE_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'CELO';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'CELO_ALFAJORES';

ALTER TYPE "NetworkFamily" ADD VALUE IF NOT EXISTS 'TVM';

ALTER TYPE "TokenStandard" ADD VALUE IF NOT EXISTS 'TRC20';
