ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'ETHEREUM_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'BASE_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'OPTIMISM_SEPOLIA';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'POLYGON_AMOY';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'BNB_TESTNET';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'AVALANCHE_FUJI';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'SOLANA_DEVNET';
ALTER TYPE "Chain" ADD VALUE IF NOT EXISTS 'BITCOIN_SIGNET';
